function seqs=configSeqs(database_folder, type)
dataSet = database_folder;

switch type
    case 'UAV123_20L'
    seqs = {struct('name','bike1','path',[dataSet '\bike1\'],'startFrame',1,'endFrame',3085,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bird1','path',[dataSet '\bird1\'],'startFrame',1,'endFrame',2437,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car1','path',[dataSet '\car1\'],'startFrame',1,'endFrame',2629,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car3','path',[dataSet '\car3\'],'startFrame',1,'endFrame',1717,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car6','path',[dataSet '\car6\'],'startFrame',1,'endFrame',4861,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car8','path',[dataSet '\car8\'],'startFrame',1,'endFrame',2575,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car9','path',[dataSet '\car9\'],'startFrame',1,'endFrame',1879,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car16','path',[dataSet '\car16\'],'startFrame',1,'endFrame',1993,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group1','path',[dataSet '\group1\'],'startFrame',1,'endFrame',4873,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group2','path',[dataSet '\group2\'],'startFrame',1,'endFrame',2683,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group3','path',[dataSet '\group3\'],'startFrame',1,'endFrame',5527,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person2','path',[dataSet '\person2\'],'startFrame',1,'endFrame',2623,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person4','path',[dataSet '\person4\'],'startFrame',1,'endFrame',2743,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person5','path',[dataSet '\person5\'],'startFrame',1,'endFrame',2101,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person7','path',[dataSet '\person7\'],'startFrame',1,'endFrame',2065,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person14','path',[dataSet '\person14\'],'startFrame',1,'endFrame',2923,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person17','path',[dataSet '\person17\'],'startFrame',1,'endFrame',2347,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person19','path',[dataSet '\person19\'],'startFrame',1,'endFrame',4357,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person20','path',[dataSet '\person20\'],'startFrame',1,'endFrame',1783,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav1','path',[dataSet '\uav1\'],'startFrame',1,'endFrame',3469,'nz',6,'ext','jpg','init_rect', [0,0,0,0])};
    case 'UAV123'
    seqs = {struct('name','bike1','path',[dataSet '\bike1\'],'startFrame',1,'endFrame',3085,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bike2','path',[dataSet '\bike2\'],'startFrame',1,'endFrame',553,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bike3','path',[dataSet '\bike3\'],'startFrame',1,'endFrame',433,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bird1_1','path',[dataSet '\bird1\'],'startFrame',1,'endFrame',253,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bird1_2','path',[dataSet '\bird1\'],'startFrame',775,'endFrame',1477,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bird1_3','path',[dataSet '\bird1\'],'startFrame',1573,'endFrame',2437,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat1','path',[dataSet '\boat1\'],'startFrame',1,'endFrame',901,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat2','path',[dataSet '\boat2\'],'startFrame',1,'endFrame',799,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat3','path',[dataSet '\boat3\'],'startFrame',1,'endFrame',901,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat4','path',[dataSet '\boat4\'],'startFrame',1,'endFrame',553,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat5','path',[dataSet '\boat5\'],'startFrame',1,'endFrame',505,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat6','path',[dataSet '\boat6\'],'startFrame',1,'endFrame',805,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat7','path',[dataSet '\boat7\'],'startFrame',1,'endFrame',535,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat8','path',[dataSet '\boat8\'],'startFrame',1,'endFrame',685,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','boat9','path',[dataSet '\boat9\'],'startFrame',1,'endFrame',1399,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','building1','path',[dataSet '\building1\'],'startFrame',1,'endFrame',469,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','building2','path',[dataSet '\building2\'],'startFrame',1,'endFrame',577,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','building3','path',[dataSet '\building3\'],'startFrame',1,'endFrame',829,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','building4','path',[dataSet '\building4\'],'startFrame',1,'endFrame',787,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','building5','path',[dataSet '\building5\'],'startFrame',1,'endFrame',481,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car1_1','path',[dataSet '\car1\'],'startFrame',1,'endFrame',751,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car1_2','path',[dataSet '\car1\'],'startFrame',751,'endFrame',1627,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car1_3','path',[dataSet '\car1\'],'startFrame',1627,'endFrame',2629,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car2','path',[dataSet '\car2\'],'startFrame',1,'endFrame',1321,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car3','path',[dataSet '\car3\'],'startFrame',1,'endFrame',1717,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car4','path',[dataSet '\car4\'],'startFrame',1,'endFrame',1345,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car5','path',[dataSet '\car5\'],'startFrame',1,'endFrame',745,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car6_1','path',[dataSet '\car6\'],'startFrame',1,'endFrame',487,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car6_2','path',[dataSet '\car6\'],'startFrame',487,'endFrame',1807,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car6_3','path',[dataSet '\car6\'],'startFrame',1807,'endFrame',2953,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car6_4','path',[dataSet '\car6\'],'startFrame',2953,'endFrame',3925,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car6_5','path',[dataSet '\car6\'],'startFrame',3925,'endFrame',4861,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car7','path',[dataSet '\car7\'],'startFrame',1,'endFrame',1033,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car8_1','path',[dataSet '\car8\'],'startFrame',1,'endFrame',1357,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car8_2','path',[dataSet '\car8\'],'startFrame',1357,'endFrame',2575,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car9','path',[dataSet '\car9\'],'startFrame',1,'endFrame',1879,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car10','path',[dataSet '\car10\'],'startFrame',1,'endFrame',1405,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car11','path',[dataSet '\car11\'],'startFrame',1,'endFrame',337,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car12','path',[dataSet '\car12\'],'startFrame',1,'endFrame',499,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car13','path',[dataSet '\car13\'],'startFrame',1,'endFrame',415,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car14','path',[dataSet '\car14\'],'startFrame',1,'endFrame',1327,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car15','path',[dataSet '\car15\'],'startFrame',1,'endFrame',469,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car16_1','path',[dataSet '\car16\'],'startFrame',1,'endFrame',415,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car16_2','path',[dataSet '\car16\'],'startFrame',415,'endFrame',1993,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car17','path',[dataSet '\car17\'],'startFrame',1,'endFrame',1057,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car18','path',[dataSet '\car18\'],'startFrame',1,'endFrame',1207,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...  
        struct('name','group1_1','path',[dataSet '\group1\'],'startFrame',1,'endFrame',1333,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group1_2','path',[dataSet '\group1\'],'startFrame',1333,'endFrame',2515,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group1_3','path',[dataSet '\group1\'],'startFrame',2515,'endFrame',3925,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group1_4','path',[dataSet '\group1\'],'startFrame',3925,'endFrame',4873,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group2_1','path',[dataSet '\group2\'],'startFrame',1,'endFrame',907,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group2_2','path',[dataSet '\group2\'],'startFrame',907,'endFrame',1771,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group2_3','path',[dataSet '\group2\'],'startFrame',1771,'endFrame',2683,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group3_1','path',[dataSet '\group3\'],'startFrame',1,'endFrame',1567,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group3_2','path',[dataSet '\group3\'],'startFrame',1567,'endFrame',2827,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group3_3','path',[dataSet '\group3\'],'startFrame',2827,'endFrame',4369,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','group3_4','path',[dataSet '\group3\'],'startFrame',4369,'endFrame',5527,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person1','path',[dataSet '\person1\'],'startFrame',1,'endFrame',799,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person2_1','path',[dataSet '\person2\'],'startFrame',1,'endFrame',1189,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person2_2','path',[dataSet '\person2\'],'startFrame',1189,'endFrame',2623,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person3','path',[dataSet '\person3\'],'startFrame',1,'endFrame',643,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person4_1','path',[dataSet '\person4\'],'startFrame',1,'endFrame',1501,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person4_2','path',[dataSet '\person4\'],'startFrame',1501,'endFrame',2743,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person5_1','path',[dataSet '\person5\'],'startFrame',1,'endFrame',877,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person5_2','path',[dataSet '\person5\'],'startFrame',877,'endFrame',2101,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person6','path',[dataSet '\person6\'],'startFrame',1,'endFrame',901,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person7_1','path',[dataSet '\person7\'],'startFrame',1,'endFrame',1249,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person7_2','path',[dataSet '\person7\'],'startFrame',1249,'endFrame',2065,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person8_1','path',[dataSet '\person8\'],'startFrame',1,'endFrame',1075,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person8_2','path',[dataSet '\person8\'],'startFrame',1075,'endFrame',1525,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person9','path',[dataSet '\person9\'],'startFrame',1,'endFrame',661,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person10','path',[dataSet '\person10\'],'startFrame',1,'endFrame',1021,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person11','path',[dataSet '\person11\'],'startFrame',1,'endFrame',721,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person12_1','path',[dataSet '\person12\'],'startFrame',1,'endFrame',601,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person12_2','path',[dataSet '\person12\'],'startFrame',601,'endFrame',1621,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person13','path',[dataSet '\person13\'],'startFrame',1,'endFrame',883,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person14_1','path',[dataSet '\person14\'],'startFrame',1,'endFrame',847,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person14_2','path',[dataSet '\person14\'],'startFrame',847,'endFrame',1813,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person14_3','path',[dataSet '\person14\'],'startFrame',1813,'endFrame',2923,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person15','path',[dataSet '\person15\'],'startFrame',1,'endFrame',1339,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person16','path',[dataSet '\person16\'],'startFrame',1,'endFrame',1147,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person17_1','path',[dataSet '\person17\'],'startFrame',1,'endFrame',1501,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person17_2','path',[dataSet '\person17\'],'startFrame',1501,'endFrame',2347,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person18','path',[dataSet '\person18\'],'startFrame',1,'endFrame',1393,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person19_1','path',[dataSet '\person19\'],'startFrame',1,'endFrame',1243,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person19_2','path',[dataSet '\person19\'],'startFrame',1243,'endFrame',2791,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person19_3','path',[dataSet '\person19\'],'startFrame',2791,'endFrame',4357,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person20','path',[dataSet '\person20\'],'startFrame',1,'endFrame',1783,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person21','path',[dataSet '\person21\'],'startFrame',1,'endFrame',487,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person22','path',[dataSet '\person22\'],'startFrame',1,'endFrame',199,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person23','path',[dataSet '\person23\'],'startFrame',1,'endFrame',397,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','truck1','path',[dataSet '\truck1\'],'startFrame',1,'endFrame',463,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','truck2','path',[dataSet '\truck2\'],'startFrame',1,'endFrame',385,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','truck3','path',[dataSet '\truck3\'],'startFrame',1,'endFrame',535,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','truck4_1','path',[dataSet '\truck4\'],'startFrame',1,'endFrame',577,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),... 
        struct('name','truck4_2','path',[dataSet '\truck4\'],'startFrame',577,'endFrame',1261,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),... 
        struct('name','uav1_1','path',[dataSet '\uav1\'],'startFrame',1,'endFrame',1555,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav1_2','path',[dataSet '\uav1\'],'startFrame',1555,'endFrame',2377,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav1_3','path',[dataSet '\uav1\'],'startFrame',2473,'endFrame',3469,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav2','path',[dataSet '\uav2\'],'startFrame',1,'endFrame',133,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav3','path',[dataSet '\uav3\'],'startFrame',1,'endFrame',265,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav4','path',[dataSet '\uav4\'],'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav5','path',[dataSet '\uav5\'],'startFrame',1,'endFrame',139,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav6','path',[dataSet '\uav6\'],'startFrame',1,'endFrame',109,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav7','path',[dataSet '\uav7\'],'startFrame',1,'endFrame',373,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','uav8','path',[dataSet '\uav8\'],'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard1','path',[dataSet '\wakeboard1\'],'startFrame',1,'endFrame',421,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard2','path',[dataSet '\wakeboard2\'],'startFrame',1,'endFrame',733,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard3','path',[dataSet '\wakeboard3\'],'startFrame',1,'endFrame',823,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard4','path',[dataSet '\wakeboard4\'],'startFrame',1,'endFrame',697,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard5','path',[dataSet '\wakeboard5\'],'startFrame',1,'endFrame',1675,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard6','path',[dataSet '\wakeboard6\'],'startFrame',1,'endFrame',1165,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard7','path',[dataSet '\wakeboard7\'],'startFrame',1,'endFrame',199,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard8','path',[dataSet '\wakeboard8\'],'startFrame',1,'endFrame',1543,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard9','path',[dataSet '\wakeboard9\'],'startFrame',1,'endFrame',355,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','wakeboard10','path',[dataSet '\wakeboard10\'],'startFrame',1,'endFrame',469,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car1_s','path',[dataSet '\car1_s\'],'startFrame',1,'endFrame',1475,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car2_s','path',[dataSet '\car2_s\'],'startFrame',1,'endFrame',320,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car3_s','path',[dataSet '\car3_s\'],'startFrame',1,'endFrame',1300,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car4_s','path',[dataSet '\car4_s\'],'startFrame',1,'endFrame',830,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person1_s','path',[dataSet '\person1_s\'],'startFrame',1,'endFrame',1600,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person2_s','path',[dataSet '\person2_s\'],'startFrame',1,'endFrame',250,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person3_s','path',[dataSet '\person3_s\'],'startFrame',1,'endFrame',505,'nz',6,'ext','jpg','init_rect', [0,0,0,0])};
    case 'UAV123_10fps'
    seqs = {
        struct('name','bike1','path',[dataSet '\bike1\'],'startFrame',1,'endFrame',1029,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','bike2','path',[dataSet '\bike2\'],'startFrame',1,'endFrame',185,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','bike3','path',[dataSet '\bike3\'],'startFrame',1,'endFrame',145,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','bird1_1','path',[dataSet '\bird1\'],'startFrame',1,'endFrame',85,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','bird1_2','path',[dataSet '\bird1\'],'startFrame',259,'endFrame',493,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','bird1_3','path',[dataSet '\bird1\'],'startFrame',525,'endFrame',813,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat1','path',[dataSet '\boat1\'],'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat2','path',[dataSet '\boat2\'],'startFrame',1,'endFrame',267,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat3','path',[dataSet '\boat3\'],'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat4','path',[dataSet '\boat4\'],'startFrame',1,'endFrame',185,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat5','path',[dataSet '\boat5\'],'startFrame',1,'endFrame',169,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat6','path',[dataSet '\boat6\'],'startFrame',1,'endFrame',269,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat7','path',[dataSet '\boat7\'],'startFrame',1,'endFrame',179,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat8','path',[dataSet '\boat8\'],'startFrame',1,'endFrame',229,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','boat9','path',[dataSet '\boat9\'],'startFrame',1,'endFrame',467,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','building1','path',[dataSet '\building1\'],'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','building2','path',[dataSet '\building2\'],'startFrame',1,'endFrame',193,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','building3','path',[dataSet '\building3\'],'startFrame',1,'endFrame',277,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','building4','path',[dataSet '\building4\'],'startFrame',1,'endFrame',263,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','building5','path',[dataSet '\building5\'],'startFrame',1,'endFrame',161,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car1_1','path',[dataSet '\car1\'],'startFrame',1,'endFrame',251,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car1_2','path',[dataSet '\car1\'],'startFrame',251,'endFrame',543,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car1_3','path',[dataSet '\car1\'],'startFrame',543,'endFrame',877,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car2','path',[dataSet '\car2\'],'startFrame',1,'endFrame',441,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car3','path',[dataSet '\car3\'],'startFrame',1,'endFrame',573,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car4','path',[dataSet '\car4\'],'startFrame',1,'endFrame',449,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car5','path',[dataSet '\car5\'],'startFrame',1,'endFrame',249,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car6_1','path',[dataSet '\car6\'],'startFrame',1,'endFrame',163,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car6_2','path',[dataSet '\car6\'],'startFrame',163,'endFrame',603,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car6_3','path',[dataSet '\car6\'],'startFrame',603,'endFrame',985,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car6_4','path',[dataSet '\car6\'],'startFrame',985,'endFrame',1309,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car6_5','path',[dataSet '\car6\'],'startFrame',1309,'endFrame',1621,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car7','path',[dataSet '\car7\'],'startFrame',1,'endFrame',345,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car8_1','path',[dataSet '\car8\'],'startFrame',1,'endFrame',453,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car8_2','path',[dataSet '\car8\'],'startFrame',453,'endFrame',859,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car9','path',[dataSet '\car9\'],'startFrame',1,'endFrame',627,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car10','path',[dataSet '\car10\'],'startFrame',1,'endFrame',469,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car11','path',[dataSet '\car11\'],'startFrame',1,'endFrame',113,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car12','path',[dataSet '\car12\'],'startFrame',1,'endFrame',167,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car13','path',[dataSet '\car13\'],'startFrame',1,'endFrame',139,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car14','path',[dataSet '\car14\'],'startFrame',1,'endFrame',443,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car15','path',[dataSet '\car15\'],'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car16_1','path',[dataSet '\car16\'],'startFrame',1,'endFrame',139,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car16_2','path',[dataSet '\car16\'],'startFrame',139,'endFrame',665,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car17','path',[dataSet '\car17\'],'startFrame',1,'endFrame',353,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car18','path',[dataSet '\car18\'],'startFrame',1,'endFrame',403,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group1_1','path',[dataSet '\group1\'],'startFrame',1,'endFrame',445,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group1_2','path',[dataSet '\group1\'],'startFrame',445,'endFrame',839,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group1_3','path',[dataSet '\group1\'],'startFrame',839,'endFrame',1309,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group1_4','path',[dataSet '\group1\'],'startFrame',1309,'endFrame',1625,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group2_1','path',[dataSet '\group2\'],'startFrame',1,'endFrame',303,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group2_2','path',[dataSet '\group2\'],'startFrame',303,'endFrame',591,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group2_3','path',[dataSet '\group2\'],'startFrame',591,'endFrame',895,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group3_1','path',[dataSet '\group3\'],'startFrame',1,'endFrame',523,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group3_2','path',[dataSet '\group3\'],'startFrame',523,'endFrame',943,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group3_3','path',[dataSet '\group3\'],'startFrame',943,'endFrame',1457,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','group3_4','path',[dataSet '\group3\'],'startFrame',1457,'endFrame',1843,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person1','path',[dataSet '\person1\'],'startFrame',1,'endFrame',267,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person2_1','path',[dataSet '\person2\'],'startFrame',1,'endFrame',397,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person2_2','path',[dataSet '\person2\'],'startFrame',397,'endFrame',875,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person3','path',[dataSet '\person3\'],'startFrame',1,'endFrame',215,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person4_1','path',[dataSet '\person4\'],'startFrame',1,'endFrame',501,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person4_2','path',[dataSet '\person4\'],'startFrame',501,'endFrame',915,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person5_1','path',[dataSet '\person5\'],'startFrame',1,'endFrame',293,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person5_2','path',[dataSet '\person5\'],'startFrame',293,'endFrame',701,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person6','path',[dataSet '\person6\'],'startFrame',1,'endFrame',301,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person7_1','path',[dataSet '\person7\'],'startFrame',1,'endFrame',417,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person7_2','path',[dataSet '\person7\'],'startFrame',417,'endFrame',689,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person8_1','path',[dataSet '\person8\'],'startFrame',1,'endFrame',359,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person8_2','path',[dataSet '\person8\'],'startFrame',359,'endFrame',509,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person9','path',[dataSet '\person9\'],'startFrame',1,'endFrame',221,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person10','path',[dataSet '\person10\'],'startFrame',1,'endFrame',341,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person11','path',[dataSet '\person11\'],'startFrame',1,'endFrame',241,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person12_1','path',[dataSet '\person12\'],'startFrame',1,'endFrame',201,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person12_2','path',[dataSet '\person12\'],'startFrame',201,'endFrame',541,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person13','path',[dataSet '\person13\'],'startFrame',1,'endFrame',295,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person14_1','path',[dataSet '\person14\'],'startFrame',1,'endFrame',283,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person14_2','path',[dataSet '\person14\'],'startFrame',283,'endFrame',605,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person14_3','path',[dataSet '\person14\'],'startFrame',605,'endFrame',975,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person15','path',[dataSet '\person15\'],'startFrame',1,'endFrame',447,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person16','path',[dataSet '\person16\'],'startFrame',1,'endFrame',383,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person17_1','path',[dataSet '\person17\'],'startFrame',1,'endFrame',501,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person17_2','path',[dataSet '\person17\'],'startFrame',501,'endFrame',783,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person18','path',[dataSet '\person18\'],'startFrame',1,'endFrame',465,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person19_1','path',[dataSet '\person19\'],'startFrame',1,'endFrame',415,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person19_2','path',[dataSet '\person19\'],'startFrame',415,'endFrame',931,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person19_3','path',[dataSet '\person19\'],'startFrame',931,'endFrame',1453,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person20','path',[dataSet '\person20\'],'startFrame',1,'endFrame',595,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person21','path',[dataSet '\person21\'],'startFrame',1,'endFrame',163,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person22','path',[dataSet '\person22\'],'startFrame',1,'endFrame',67,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','person23','path',[dataSet '\person23\'],'startFrame',1,'endFrame',133,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','truck1','path',[dataSet '\truck1\'],'startFrame',1,'endFrame',155,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','truck2','path',[dataSet '\truck2\'],'startFrame',1,'endFrame',129,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','truck3','path',[dataSet '\truck3\'],'startFrame',1,'endFrame',179,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','truck4_1','path',[dataSet '\truck4\'],'startFrame',1,'endFrame',193,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','truck4_2','path',[dataSet '\truck4\'],'startFrame',193,'endFrame',421,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav1_1','path',[dataSet '\uav1\'],'startFrame',1,'endFrame',519,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav1_2','path',[dataSet '\uav1\'],'startFrame',519,'endFrame',793,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav1_3','path',[dataSet '\uav1\'],'startFrame',825,'endFrame',1157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav2','path',[dataSet '\uav2\'],'startFrame',1,'endFrame',45,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav3','path',[dataSet '\uav3\'],'startFrame',1,'endFrame',89,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav4','path',[dataSet '\uav4\'],'startFrame',1,'endFrame',53,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav5','path',[dataSet '\uav5\'],'startFrame',1,'endFrame',47,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav6','path',[dataSet '\uav6\'],'startFrame',1,'endFrame',37,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav7','path',[dataSet '\uav7\'],'startFrame',1,'endFrame',125,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','uav8','path',[dataSet '\uav8\'],'startFrame',1,'endFrame',101,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard1','path',[dataSet '\wakeboard1\'],'startFrame',1,'endFrame',141,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard2','path',[dataSet '\wakeboard2\'],'startFrame',1,'endFrame',245,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard3','path',[dataSet '\wakeboard3\'],'startFrame',1,'endFrame',275,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard4','path',[dataSet '\wakeboard4\'],'startFrame',1,'endFrame',233,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard5','path',[dataSet '\wakeboard5\'],'startFrame',1,'endFrame',559,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard6','path',[dataSet '\wakeboard6\'],'startFrame',1,'endFrame',389,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard7','path',[dataSet '\wakeboard7\'],'startFrame',1,'endFrame',67,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard8','path',[dataSet '\wakeboard8\'],'startFrame',1,'endFrame',515,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard9','path',[dataSet '\wakeboard9\'],'startFrame',1,'endFrame',119,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','wakeboard10','path',[dataSet '\wakeboard10\'],'startFrame',1,'endFrame',157,'nz',6,'ext','jpg','init_rect',[0,0,0,0]),...
        struct('name','car1_s','path',[dataSet '\car1_s\'],'startFrame',1,'endFrame',492,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car2_s','path',[dataSet '\car2_s\'],'startFrame',1,'endFrame',107,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car3_s','path',[dataSet '\car3_s\'],'startFrame',1,'endFrame',434,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','car4_s','path',[dataSet '\car4_s\'],'startFrame',1,'endFrame',277,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person1_s','path',[dataSet '\person1_s\'],'startFrame',1,'endFrame',534,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person2_s','path',[dataSet '\person2_s\'],'startFrame',1,'endFrame',84,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','person3_s','path',[dataSet '\person3_s\'],'startFrame',1,'endFrame',169,'nz',6,'ext','jpg','init_rect', [0,0,0,0]),...
        };
end
